service: charli-test-api

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: eu-west-2

package:
  exclude:
    - terraform/**

functions:
  app:
    handler: index.handler
    events:
      - http:
          path: /{proxy+}
          method: ANY
          cors:
            origin: "*"
            allowCredentials: false
