service: charli-test-api

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: eu-west-2

package:
  individually: true
  exclude:
    - "*/**"

functions:
  app:
    handler: index.handler
    package:
      include:
        - index.js
        - package.json
    events:
      - http:
          path: /{proxy+}
          method: ANY
          cors:
            origin: "*"
            allowCredentials: false
